//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("Atlas Patcher (SCP:SL)")]
[assembly: System.Reflection.AssemblyDescription("The bootstrap patcher for the Atlas framework, targeted at SCP:SL.")]
[assembly: System.Reflection.AssemblyCompany("Ashe")]
[assembly: System.Reflection.AssemblyProduct("Atlas Patcher")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Ashe 2019")]
[assembly: System.Runtime.InteropServices.Guid("BCF2C99A-2B36-40A9-AAAC-A2F1873BA3CA")]


