//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("Atlas Patcher")]
[assembly: System.Reflection.AssemblyDescription("The base bootstrap patcher for the Atlas framework.")]
[assembly: System.Reflection.AssemblyCompany("Ashe")]
[assembly: System.Reflection.AssemblyProduct("Atlas Patcher")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Ashe 2019")]
[assembly: System.Runtime.InteropServices.Guid("DDBA0843-72CC-4A95-A631-DF617BBA5323")]


