//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("Atlas")]
[assembly: System.Reflection.AssemblyDescription("A modding framework for .NET applications.")]
[assembly: System.Reflection.AssemblyCompany("Ashe")]
[assembly: System.Reflection.AssemblyProduct("Atlas")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Ashe 2019")]
[assembly: System.Runtime.InteropServices.Guid("C1256921-8467-44B9-B9A8-1D1EAE10B43A")]


